---
  # docker container postgres settings
  postgresName: iroha_postgres
  postgresUser: psql
  postgresPassword: psql

  confPath: /opt/docker/iroha/conf   # left for Ubuntu playbook (might be different for other distros)
  iroha_net: iroha_network  # name of docker network
  key: 0    # node ID counter init value