#---
  - hosts: iroha-nodes
    gather_facts: False
    tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  - hosts: locals
    roles:
      - { role: iroha-gen }

  - hosts: iroha-nodes
    gather_facts: true
    roles:
      - { role: docker, tags: docker }
      - { role: iroha-node }
