---
  - setup:

  - name: Make conf dir
    file:
      path: "{{ confPath }}{{ item }}"
      state: directory
      mode: 0755
      owner: root
    with_sequence: start=0 end=6

  - name: generate compose
    template:
      src: docker-compose.yml.j2
      dest: "/tmp/docker-compose.yml"


  - name: generate configs
    template:
      src: config.j2
      dest: "{{ confPath }}{{ item }}/config.sample"
    with_sequence: start=0 end=6


  - name: copy genesis block
    copy:
      src: "{{ filesDir }}/genesis.block"
      dest: "{{ confPath }}{{ item }}/genesis.block"
    with_sequence: start=0 end=6

  - name: copy public keys
    copy:
      src: "{{ filesDir }}/node{{ key + item | int}}.pub"
      dest: "{{ confPath }}{{ item }}/"
    with_sequence: start=0 end=6

  - name: copy private keys
    copy:
      src: "{{ filesDir }}/node{{ key + item | int}}.priv"
      dest: "{{ confPath }}{{ item }}/"
    with_sequence: start=0 end=6

  - name: run docker compose
    command: docker-compose up -d
    args:
      chdir: "{{ composeDir }}"